import Head from 'next/head'
import type { NextPage } from 'next'
import { Inter } from '@next/font/google'
import Header from '../components/header/Header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Wyzer's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header/>

    {/* Hero */}

    {/* About */}

    {/* Experience */}

    {/* Skills */}
    
    {/* Projects */}

     {/* Contact Me */}



    </>
  )
}
